feat(cast): add --flashbots to use flashbots rpc url
gakonst/foundry pull request #369
Opened 2022-01-04 21:54 UTC by tlancina

Saw this so I thought I'd give it a shot: https://twitter.com/gakonst/status/1478463108100366339.

Sadly, I am missing something with how `structopt` works, since the output is messed up:

```
cast-send 0.1.0
The wallet options can either be: 1. Ledger 2. Trezor 3. Mnemonic (via file path) 4. Keystore (via file path) 5. Private
Key (cleartext in CLI) 6. Private Key (interactively via secure prompt)

USAGE:
    cast send [FLAGS] [OPTIONS] <to> <sig> --rpc-url <rpc-url> [args]...

FLAGS:
        --flashbots      use the flashbots RPC URL
    -h, --help           Prints help information
    -i, --interactive    Interactive prompt to insert your private key
```

If you have any thoughts let me know, figured I'd push this up while I try to figure it out.

2022-01-05 08:48 UTC, gakonst requested changes

2022-01-05 08:48 UTC, gakonst commented on cli/src/opts/cast.rs
> +        flashbots: bool,
Let's maybe pull `flashbots` inside `EthereumOpts` and make `eth.rpc_url` an `Option<String>`, then add a helper function `eth.rpc_url() -> Result<&str>` which does:

```
if flashbots {
      Ok(FLASHBOTS_URL)
} else {
     self.rpc_url.ok_or(|| eyre::Error::msg("no Ethereum RPC provided, maybe you forgot to set the --rpc-url or the ETH_RPC_URL parameter? Alternatively, consider using the --flashbots flag to get frontrunning protection")
}

2022-01-06 06:23 UTC, gakonst approved these changes
Very nice!

2022-01-06 06:23 UTC, gakonst commented on cli/src/opts/mod.rs
> +    #[structopt(long, help = "Use the flashbots RPC URL")]
```suggestion
    #[structopt(long, help = "Use the flashbots RPC URL (https://rpc.flashbots.net)")]
```

2022-01-06 06:23 UTC, merged

2022-01-06 10:51 UTC, 0xRobin commented
Linked issue that should be closed.
https://github.com/gakonst/foundry/issues/368