fix(evm-adapters): index out of bounds panic if expected length > input length
gakonst/foundry pull request #533
Opened 2022-01-21 20:53 UTC by ArtificialPB

Right now, if you provide `calldata`-  via `expectCall` cheatcode - with more parameters than actual call input, it causes a panic. 

This should be handled gracefully. If no match was found it fails the test anyway.

2022-01-21 22:12 UTC, gakonst approved these changes

2022-01-21 22:13 UTC, gakonst commented
@ArtificialPB could you add a cheatcode test which hits this failure mode?

2022-01-21 22:13 UTC, gakonst requested changes
Nice catch

2022-01-22 12:26 UTC, ArtificialPB commented
@gakonst added

2022-01-22 13:18 UTC, gakonst approved these changes

2022-01-22 13:18 UTC, merged

2022-01-22 13:19 UTC, gakonst commented
perf - thank you!