Cast interface events
gakonst/foundry pull request #664
Opened 2022-02-03 23:03 UTC by Boda805

## Solution

Solves #594

2022-02-03 23:07 UTC, Boda805 commented
Had some oddity with f97aa47, git said I had changes to foundryup/install somehow, but file looked the same and I couldn't discard, so I tried to stop tracking.

2022-02-04 04:02 UTC, mds1 commented
Tested on two contracts and works great! 👌 Neither had any ABIEncoderV2 params, as I'm not sure of contracts offhand to test that with though

2022-02-04 08:27 UTC, gakonst requested changes
LGTM, small refactor needed, and if you can also add to the tests

2022-02-04 08:27 UTC, gakonst commented on utils/src/lib.rs
> +    let (kind, v2_struct) = match param.kind {
Can you refactor this to be reused across both functions and events to avoid code duplication?

2022-02-05 20:17 UTC, merged

2022-02-06 16:08 UTC, Boda805 commented
Thanks for helping get finished up, I was working on but would've taken bit longer. One nit I was going to fix was the 's' should probably be dropped off of format_event_params.