feat(forge create): read calldata from file
gakonst/foundry pull request #674
Opened 2022-02-04 22:34 UTC by tynes

## Motivation
I want to be able to deploy a transaction with large constructor args. If passed via `argv` they are too large.

## Solution

It is possible to create a transaction where the
calldata is too large to be passed via `argv`.
See https://wiki.debian.org/CommonErrorMessages/ArgumentListTooLong
for more information on this limitation. To make it
possible to create these large transactions, update
`forge create` so that it can read the calldata
from a file. Now if there is a single argument
passed to `--constructor-args`, it will check to
see if it is a path to a file and if there is a file
then it will read that file and parse it as a space
delimited string.

There are a security implication here, if somebody is able
to get a file on the filesystem that mirrors an actual
calldata argument, then the file could be read and used instead of
the actual argument.

An alternative solution would be to add another flag that is meant to be
a path to a file and enforce that only 1 of the flags is passed for passing through
calldata. I feel like there is a more idomatic rust solution compared to
my implementation, so open to any feedback. This should also include
doc updates so people know this feature exists

2022-02-04 22:47 UTC, tynes commented
The more that I think about this, the more that I think that this functionality should be implemented via a different flag. Thoughts?

2022-02-05 01:03 UTC, mattsse commented
hmm, can't think of any side effects if we check whether the input is a file, but leaning towards making this a separate flag that `conflicts_with = constructor-args`, explicitly for reading from file, many `contructor-file`? 
cc @gakonst

2022-02-05 09:25 UTC, gakonst requested changes
Good idea - Let's do with a separate flag "--constructor-args-path" or something similar and conflicts_with as Matt said

2022-02-06 02:43 UTC, tynes commented
> Good idea - Let's do with a separate flag "--constructor-args-path" or something similar and conflicts_with as Matt said

I've updated this PR to add the `--constructor-args-path` flag

2022-02-06 02:44 UTC, tynes commented on cli/src/cmd/create.rs
>          {
I ran `cargo fmt` and it produced this diff, happy to revert if you'd like

2022-02-06 08:27 UTC, gakonst commented on cli/src/cmd/create.rs
> +                }
```suggestion
                let constructor_args = if let Some(ref constructor_args_path) = self.constructor_args_path {
                    if !std::path::Path::new(&constructor_args_path).exists() {
                        eyre::bail!("constructor args path not found");
                    }
                    let file = fs::read_to_string(constructor_args_path)?;
                    file.split(" ").map(|s| s.to_string()).collect::<Vec<String>>()
                } else {
                    self.constructor_args
                };
```

this is a bit better

2022-02-06 08:27 UTC, gakonst commented on cli/src/cmd/create.rs
> +        constructor_args: &Vec<String>,
```suggestion
        constructor_args: &[String],
```

2022-02-06 18:43 UTC, tynes commented on cli/src/cmd/create.rs
> +                }
Ah good looks getting rid of the `mut`

2022-02-06 21:48 UTC, gakonst approved these changes
nice work - fixed the nightly fmt/lints, had to update to latest locally

2022-02-06 21:48 UTC, merged