fix(forge/install): check github repo name is valid
gakonst/foundry pull request #719
Opened 2022-02-11 10:55 UTC by jrhe

## Motivation

`forge install` doesn't check to see if a valid github repo name has been specified when using the shorthand method for installing packages e.g. `forge install solmate`.

See #712.

## Solution

Adds a (basic) regex to check the format of the github repo name, and throws an error if invalid.

2022-02-11 11:01 UTC, mattsse requested changes
thanks for this

2022-02-11 21:19 UTC, tdudz commented on cli/src/opts/forge.rs
> +            lazy_static! {
just curious, why is `once_cell` considered better?

2022-02-12 15:47 UTC, gakonst commented on cli/src/opts/forge.rs
> +            lazy_static! {
https://users.rust-lang.org/t/lazy-static-vs-once-cell-oncecell/58578/3

2022-02-12 16:00 UTC, merged

2022-02-12 18:58 UTC, sambacha commented
🙏💯

thanks