feat(etherscan directory output)
gakonst/foundry pull request #816
Opened 2022-02-26 20:28 UTC by jubos

* Inspired by etherscan.deth.net, this feature will expand a verified contract's
  source code paths to a directory for easy consumption with your favorite
  editor / IDE.

* Tested via the following examples that test a few of the edge cases.
> cargo run --bin cast -- etherscan-source 0x8d04a8c79cEB0889Bdd12acdF3Fa9D207eD3Ff63 -d blitmap
This results in a directory tree with all the source files of the contract.

> cargo run --bin cast -- etherscan-source 0xBB9bc244D798123fDe783fCc1C72d3Bb8C189413 -d thedao
This results in a single file output.

> cargo run --bin cast -- etherscan-source 0xb5c31a0e22cae98ac08233e512bd627885aa24e5 -d unverified
This returns an error since the following contract is not verified yet on Etherscan

## Motivation

When learning about smart contracts it is a nice improvement to able the browse the contract code in your normal developer environment.

## Solution

This feature parses the etherscan API source structure and writes it to directory.

2022-02-26 21:00 UTC, mattsse requested changes
awesome!
just tested this and works as expected.
since this is primarily etherscan related, I'd suggest we add support for this directly into ethers-etherscan::ContractMetadata instead

perhaps some like `fn into_source_tree|expand() -> Result<SourceTree>` and the sourcetree (maybe a better name?) object would essentially hold path and content of all files?

and then `SourceTree::write_to(dir: Path)` would dump them into a dir

2022-02-26 21:00 UTC, mattsse commented on cast/src/lib.rs
> +        if meta.items.iter().any(|item| item.abi == "Contract source code not verified") {
we should handle this while deserializing the response in the etherscan client and make this an Option. Mind opening an issue for this on ethers or even a PR?

2022-02-26 21:00 UTC, mattsse commented on cast/src/lib.rs
> +            &etherscan_source[etherscan_source.len() - 2..] == "}}"
use `.ends_with` and `starts_with` instead

2022-02-26 21:00 UTC, mattsse commented on cast/src/lib.rs
> +            if os_str == "." || os_str == ".." {
you can use `x == Component::CurDir || x == Component::ParentDir` instead

2022-02-26 21:00 UTC, mattsse commented on cast/src/lib.rs
> +            let parsed: EtherscanSourceJsonMetadata = serde_json::from_str(&json)?;
think this should be `json` instead of `&json`

2022-02-26 21:00 UTC, mattsse commented on cast/src/lib.rs
> +    Path::new(path).components().filter(|x| x.as_os_str() != "..").collect::<PathBuf>()
`Component::ParentDir`

2022-03-04 13:55 UTC, gakonst commented
Hey @jubos thanks for taking a stab at this PR! Wonder what your plans are for getting this over the line? Happy to help with any specific code you don't have time to write

2022-03-04 16:29 UTC, jubos commented
Planning to get it over the line this weekend.

2022-03-05 02:20 UTC, jubos commented
I made this PR to ethers-rs: https://github.com/gakonst/ethers-rs/pull/990 that incorporates a lot of @mattsse's suggestions.  We can discuss over there and this PR will end up being very abbreviated.

2022-03-05 19:41 UTC, mattsse commented
> I made this PR to ethers-rs: [gakonst/ethers-rs#990](https://github.com/gakonst/ethers-rs/pull/990) that incorporates a lot of @mattsse's suggestions. We can discuss over there and this PR will end up being very abbreviated.

Great! so we can drastically simplify this once merged?

2022-03-07 17:58 UTC, gakonst commented
@jubos merged on ethers!

2022-03-19 16:33 UTC, jubos commented
Added this PR to centralize the error handling for unverified contracts.  https://github.com/gakonst/ethers-rs/pull/1065.

Once that lands, can simplify this and other callsites in foundry.

2022-03-20 06:47 UTC, gakonst approved these changes

2022-03-20 16:18 UTC, mattsse approved these changes
lgtm

2022-03-20 17:00 UTC, gakonst commented
This is great @jubos! Love it. 

Testing `cargo run --bin cast -- etherscan-source 0x8d04a8c79cEB0889Bdd12acdF3Fa9D207eD3Ff63 -d blitmap` it creates a `blitmap/Blitmap/` directory, wonder if instead it should be just `blitmap`?

Similarly, testing `cargo run --bin cast -- etherscan-source 0xBB9bc244D798123fDe783fCc1C72d3Bb8C189413 -d thedao` produces `thedao/DAO/DAO` (notice that there's no `.sol` extension).

If the above 2 are unintended, do you mind addressing it so that there's no double directory and that all files have a .sol extension? Otherwise we're good for merge, and would encourage you to do a twitter ann of this as a feature :)

2022-03-24 16:09 UTC, jubos commented
Added the .sol change to ethers-rs: https://github.com/gakonst/ethers-rs/pull/1077.

We could land this commit as is and then will get this improved behavior when the ether-rs commit lands.

2022-03-24 17:04 UTC, merged